version: '3.8'

services:
  app:
    container_name: go-admin
    build: .
    ports:
      - "9876:80"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - DATA_PATH=./data
    restart: unless-stopped